---
title: "ISLR::Caravan"
author: "Sahba Salarian"
date: 'Feb. 2019'
output: pdf_document
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(fig.pos = 'H')
knitr::opts_chunk$set(warning=FALSE)
knitr::opts_chunk$set(message=FALSE)
library(xtable)
options(xtable.comment = FALSE)
library(knitr)
library(tidyverse)
library(ggplot2)
library(bestglm) 
library(stargazer)
library(corrplot)
library(car)
library(repr)
library(MASS)
library(leaps)
library(pROC)
library(ROCR)
library(caret)
library(kernlab)
library(e1071)
library(GGally)
library(ISLR)
library(earth)
opts_chunk$set(tidy.opts=list(width.cutoff=60),tidy=TRUE)
```

#Introduction



##DATA EXPLANATION




###Attribute Information

```{r}
summary(Caravan)
plot(Caravan$Purchase)
```



## Data engineering : 

In this stage the NA values of the data set has been detedcted and the rows with such values are omitted from the data set. 

```{r Omit NA , echo = FALSE}
df <- na.omit(Caravan)
#creating a data set without names:
str(df)
```


#Train/Test Split:



```{r test&cv&train, echo = FALSE}
set.seed(798102) 
split <- sample (2, nrow (df), replace= TRUE, prob = c (0.7, 0.3))
train <- df [split==1,]
test <- df [split==2,]
```



## Use caret for training machine learning models

##Use GLM to fit the model

```{r caret initialization}
#caret default
caretControl <- trainControl(method = "boot",number = 25, classProbs =  TRUE)
```


```{r trian GLM}
set.seed(3233)
modelGLM <- train(as.factor(Purchase)~., data = train, method = "glm",
                 trControl=caretControl)
summary(modelGLM)
modelGLM
```


```{r GLM Confusion Matrix}
#turn probabilities into classess and look at their frequencies:
p_modelGLM <- predict(modelGLM, test, type="prob")
p_ClassGLM <- predict(modelGLM, test)
confusionMatrix(p_ClassGLM, factor(test$Purchase))
```

##SVM
##SVMLinear
```{r trian SVM Linear}
set.seed(3233)
modelSVMLinear <- train(factor(Purchase)~., data = train, method = "svmLinear",
                 trControl=caretControl, Probs =  TRUE)
summary(modelSVMLinear)
modelSVMLinear
```


```{r}
p_modelSVMLinear <- predict(modelSVMLinear, test, "prob")
p_ClassSVMLinear <- predict(modelSVMLinear, test)
confusionMatrix(p_ClassSVMLinear, factor(test$Purchase))
```


```{r trian SVM Radial}
set.seed(3233)
modelSVMRadial <- train(factor(Purchase)~., data = train, method = "svmRadial",
                 trControl=caretControl)
summary(modelSVMRadial)
modelSVMRadial
```

```{r}
p_modelSVMRadial <- predict(modelSVMRadial, test, "prob")
p_ClasslSVMRadial <- predict(modelSVMRadial, test)
confusionMatrix(p_ClasslSVMRadial, factor(test$Purchase))
```





## Comaprison

```{r COMPARISON GLM, AIC, SVMlinear and SVMradial}
comparison<-resamples(list(GLM=modelGLM, SVMLinear=modelSVMLinear, SVMRadial=modelSVMRadial))
summary(comparison)
```




```{r ROC for GLM}
ROC_GLM <- roc(factor(test$Purchase)~p_modelGLM[,2], plot = TRUE, print.auc = TRUE,main="ROC for GLM")
```



```{r ROC for SVMlinear}
ROC_SVMlinear<- roc(factor(test$Purchase)~p_modelSVMLinear[,2], plot = TRUE, print.auc = TRUE, main="ROC for SVM withlinear kernel")
```


```{r ROC for SVMRadial}
ROC_SVMRadial<- roc(factor(test$Purchase)~p_modelSVMRadial[,2], plot = TRUE, print.auc = TRUE, main="ROC for SVM with radial kernel")
```


## MARS with penalty

```{r}
modelMARS <- earth(factor(Purchase)~., data=train, degree=2,keepxy=TRUE, ncross=3, nfold=5, penalty = -1)
```


```{r}
plot(modelMARS, which=1, col.rsq=0)
```